site_name: PURCO SA
site_url: https://test3.purcosa.co.za/user-guide

nav:
  - 'Nav 1': 'index.md'
  - 'Nav 2':
    - 'SubNav 2-1': 'civicrm.md'
    - 'SubNav 2-2': 'civicrm2.md'
  - CiviCRM:
    - 'Contacts': './civicrm/contacts.md'
    - 'Groups and tags': './civicrm/groups-and-tags.md'
    - 'Smart groups': './civicrm/smart-groups.md'
    - 'Searching and reporting': './civicrm/searching.md'
    - 'Relationships': './civicrm/relationships.md'
    - 'Events': './civicrm/what-is-civievent.md'

theme:
  name: readthedocs
  locale: en

extra_css:
  - style.css

use_directory_urls: false
