site_name: PURCO SA Staff Guide
site_url: https://test3.purcosa.co.za/user-guide/

nav:
  - Welcome: 'index.md'
  - Tenders:
    - 'Creating a Tender': './tenders/creating-a-tender.md'
    - 'Adding supporting documents': './tenders/adding-supporting-docs.md'
    - 'Tender Invitation Mailings': './tenders/tender-invitation-mailings.md'
    - 'Information Sessions': './tenders/info-sessions.md'
    - 'Q&A Management': './tenders/q-and-a-management.md'
    - 'The Tender Dashboard': './tenders/tender-dashboard.md'
  - TenderBoxes:
    - 'Allocating access': './tenderboxes/allocating-access.md'
    - 'Helping a supplier with access': './tenderboxes/supplier-access.md'
    - 'Downloading submitted files': './tenderboxes/downloading-files.md'
    - 'Publishing and unpublishing': './tenderboxes/publishing-unpublishing.md'
  - CiviCRM:
    - 'Contacts': './civicrm/contacts.md'
    - 'Groups and tags': './civicrm/groups-and-tags.md'
    - 'Smart groups': './civicrm/smart-groups.md'
    - 'Searching and reporting': './civicrm/searching.md'
    - 'Relationships': './civicrm/relationships.md'
    - 'Events':
      - 'What is CiviEvent': './civicrm/events/what-is-civievent.md'
      - 'Online event registration': './civicrm/events/online-event-registration.md'
    - 'Email':
      - 'What is CiviMail': './civicrm/email/what-is-civimail.md'
      - 'What you need to know': './civicrm/email/what-you-need-to-know.md'
      - 'Everyday tasks': './civicrm/email/everyday-tasks.md'
      - 'Mass mailings using CiviMail': './civicrm/email/mass-mailings-using-civimail.md'
      - 'Reports and analysis': './civicrm/email/reports-and-analysis.md'

theme:
  name: mkdocs
  locale: en
  navigation_depth: 2

extra_css:
  - style.css

use_directory_urls: false
