site_name: PURCO SA Staff Guide
site_url: https://purcosa.co.za/staff-guide/

nav:
  - Welcome: 'index.md'
  - Tenders:
    - 'Creating a Tender': './tenders/creating-a-tender.md'
    - 'Invitation Mailings': './tenders/tender-invitation-mailings.md'
    - 'Information Sessions': './tenders/info-sessions.md'
    - 'Q&A Management': './tenders/q-and-a-management.md'
    - 'The Tender Dashboard': './tenders/tender-dashboard.md'
  - TenderBoxes:
    - 'Creating a TenderBox': './tenderboxes/creating-a-tenderbox.md'
    - 'Allocating Access': './tenderboxes/allocating-access.md'
    - 'Publishing and Unpublishing': './tenderboxes/publishing-unpublishing.md'
    - 'Helping a Supplier with Access': './tenderboxes/supplier-access.md'
    - 'Viewing & Assessing Bids': './tenderboxes/viewing-and-assessing-bids.md'
    - 'Downloading Submitted Files & Data': './tenderboxes/downloading-files.md'
  - Contracts:
    - 'Viewing & Exporting Contracts': './contracts/viewing-contracts.md'
    - 'Contract Document Management': './contracts/managing-contract-documents.md'
  - CiviCRM:
    - 'Contacts': './civicrm/contacts.md'
    - 'Groups and tags': './civicrm/groups-and-tags.md'
    - 'Smart groups': './civicrm/smart-groups.md'
    - 'Searching and reporting': './civicrm/searching.md'
    - 'Relationships': './civicrm/relationships.md'
    - Events: './civicrm/events/what-is-civievent.md'
      - 'What is CiviEvent': './civicrm/events/what-is-civievent.md'
      - 'Online event registration': './civicrm/events/online-event-registration.md'
    - Email:
      - 'What is CiviMail': './civicrm/email/what-is-civimail.md'
      - 'What you need to know': './civicrm/email/what-you-need-to-know.md'
      - 'Everyday tasks': './civicrm/email/everyday-tasks.md'
      - 'Mass mailings using CiviMail': './civicrm/email/mass-mailings-using-civimail.md'
      - 'Reports and analysis': './civicrm/email/reports-and-analysis.md'

theme:
  name: material
  locale: en
#   navigation_depth: 2
  palette:
    primary: custom
    accent: custom
  logo: img/PURCOSAlogoreversed.png
  favicon: img/favicon.png
  features:
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.preview
    - navigation.tabs
    - navigation.tabs.sticky
    ## - navigation.sections
    - navigation.path
    - navigation.top
    - toc.integrate
    - toc.follow
    - search.suggest
    - search.highlight
  toc:
    collapse: true

extra_css:
  - style.css

extra_javascript:
  - js/jquery-3.7.1.min.js
  - js/collapsible_integrated_toc.js

use_directory_urls: false
