site_name: PURCO SA

nav:
  - 'Nav 1': 'index.md'
  - 'Nav 2':
    - 'SubNav 2-1': 'civicrm.md'
    - 'SubNav 2-2': 'civicrm2.md'
  - CiviCRM:
    - 'Searching and reporting': './civicrm/searching.md'

theme:
  name: readthedocs
  locale: en

extra_css:
  - style.css

use_directory_urls: true
